Repository runtipi/runtipi, pull requests merged in 2024-06, with the labels that each got.

#1456 feat(docker-tamplate): include addPorts and readOnly in volumes
  .prettierignore
  packages/worker/src/config/docker-templates.ts
Labels: size/M

#1459 release: 3.4.0
  .devcontainer/devcontainer.json
  .github/workflows/nightly-release.yml
  .prettierignore
  Dockerfile
  Dockerfile.dev
  docker-compose.dev.yml
  docker-compose.prod.yml
  next.config.mjs
  package.json
  packages/shared/package.json
  packages/shared/src/schemas/socket-schemas.ts
  packages/worker/package.json
  packages/worker/src/config/docker-templates.ts
  packages/worker/src/lib/docker/docker-helpers.ts
  packages/worker/src/lib/socket/SocketManager.ts
  pnpm-lock.yaml
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/(dashboard)/app-store/[id]/components/AppDetailsContainer/AppDetailsContainer.tsx
  src/app/(dashboard)/app-store/[id]/components/AppDetailsTabs/AppDetailsTabs.tsx
  src/app/(dashboard)/app-store/[id]/components/AppDetailsTabs/AppLogs.tsx
  src/app/(dashboard)/settings/components/LogsContainer/LogsContainer.tsx
  src/app/(dashboard)/settings/components/LogsContainer/index.ts
  src/app/(dashboard)/settings/components/SettingsTabTriggers/SettingsTabTriggers.tsx
  src/app/(dashboard)/settings/page.tsx
  src/app/(dashboard)/test-error/page.tsx
  src/app/api/test-error/route.ts
  src/app/components/LogsTerminal/LogsTerminal.module.scss
  src/app/components/LogsTerminal/LogsTerminal.tsx
  src/app/global-error.jsx
  src/app/global-error.tsx
  src/client/messages/en.json
  src/client/messages/es-ES.json
  src/instrumentation.ts
  src/lib/socket/useSocket.test.ts
  src/lib/socket/useSocket.ts
  vitest.workspace.ts
Labels: size/XXL

#1467 New Crowdin updates
  src/client/messages/af-ZA.json
  src/client/messages/ar-SA.json
  src/client/messages/ca-ES.json
  src/client/messages/cs-CZ.json
  src/client/messages/da-DK.json
  src/client/messages/de-DE.json
  src/client/messages/el-GR.json
  src/client/messages/en-US.json
  src/client/messages/es-ES.json
  src/client/messages/fi-FI.json
  src/client/messages/fr-FR.json
  src/client/messages/he-IL.json
  src/client/messages/hu-HU.json
  src/client/messages/it-IT.json
  src/client/messages/ja-JP.json
  src/client/messages/ko-KR.json
  src/client/messages/nl-NL.json
  src/client/messages/no-NO.json
  src/client/messages/pl-PL.json
  src/client/messages/pt-BR.json
  src/client/messages/pt-PT.json
  src/client/messages/ro-RO.json
  src/client/messages/ru-RU.json
  src/client/messages/sr-SP.json
  src/client/messages/sv-SE.json
  src/client/messages/tr-TR.json
  src/client/messages/uk-UA.json
  src/client/messages/vi-VN.json
  src/client/messages/zh-CN.json
  src/client/messages/zh-TW.json
Labels: size/XL

#1471 release: 3.4.1
  .all-contributorsrc
  README.md
  docker-compose.dev.yml
  package.json
  packages/shared/package.json
  packages/worker/package.json
  packages/worker/src/lib/docker/docker-helpers.ts
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/app/(dashboard)/app-store/[id]/components/AppDetailsTabs/AppDetailsTabTriggers.tsx
  src/app/(dashboard)/app-store/[id]/components/AppDetailsTabs/AppDetailsTabs.tsx
  src/app/(dashboard)/app-store/[id]/components/AppDetailsTabs/AppLogs.tsx
  src/app/(dashboard)/settings/components/LogsContainer/LogsContainer.tsx
  src/app/components/LogsTerminal/LogsTerminal.tsx
  src/client/components/ClientOnly/ClientOnly.tsx
  src/client/messages/af-ZA.json
  src/client/messages/ar-SA.json
  src/client/messages/ca-ES.json
  src/client/messages/cs-CZ.json
  src/client/messages/da-DK.json
  src/client/messages/de-DE.json
  src/client/messages/el-GR.json
  src/client/messages/en-US.json
  src/client/messages/es-ES.json
  src/client/messages/fi-FI.json
  src/client/messages/fr-FR.json
  src/client/messages/he-IL.json
  src/client/messages/hu-HU.json
  src/client/messages/it-IT.json
  src/client/messages/ja-JP.json
  src/client/messages/ko-KR.json
  src/client/messages/nl-NL.json
  src/client/messages/no-NO.json
  src/client/messages/pl-PL.json
  src/client/messages/pt-BR.json
  src/client/messages/pt-PT.json
  src/client/messages/ro-RO.json
  src/client/messages/ru-RU.json
  src/client/messages/sr-SP.json
  src/client/messages/sv-SE.json
  src/client/messages/tr-TR.json
  src/client/messages/uk-UA.json
  src/client/messages/vi-VN.json
  src/client/messages/zh-CN.json
  src/client/messages/zh-TW.json
  src/shared/internationalization/locales.ts
Labels: size/XXL

#1472 refactor(docker-templates): use a builder pattern to improve readability
  packages/worker/src/config/__tests__/docker-templates.test.ts
  packages/worker/src/config/docker-templates.ts
  packages/worker/src/lib/docker/builders/docker-compose-builder.ts
  packages/worker/src/lib/docker/builders/service-builder.ts
  packages/worker/src/lib/docker/builders/traefik-labels-builder.ts
Labels: size/XL

#1473 refactor(apps.service): implement command design pattern
  .prettierignore
  src/server/queries/apps/apps.queries.ts
  src/server/services/apps/app-cache-manager.ts
  src/server/services/apps/apps.service.test.ts
  src/server/services/apps/apps.service.ts
  src/server/services/apps/commands/get-app-command.ts
  src/server/services/apps/commands/get-guest-dashboard-apps-command.ts
  src/server/services/apps/commands/get-installed-apps-command.ts
  src/server/services/apps/commands/index.ts
  src/server/services/apps/commands/install-app-command.ts
  src/server/services/apps/commands/reset-app-command.ts
  src/server/services/apps/commands/restart-app-command.ts
  src/server/services/apps/commands/start-all-apps-command.ts
  src/server/services/apps/commands/start-app-command.ts
  src/server/services/apps/commands/stop-app-command.ts
  src/server/services/apps/commands/types.ts
  src/server/services/apps/commands/uninstall-app-command.ts
  src/server/services/apps/commands/update-app-command.ts
  src/server/services/apps/commands/update-app-config-command.ts
Labels: size/XXL

#1474 New Crowdin updates
  src/client/messages/hu-HU.json
  src/client/messages/pt-BR.json
Labels: size/M

#1489 refactor(apps): create a data access class for all filesystem reading
  .eslintrc.js
  packages/shared/.eslintrc.js
  packages/shared/.prettierrc.js
  packages/shared/package.json
  packages/shared/src/index.ts
  packages/shared/src/node/helpers/typescript-helpers.ts
  packages/shared/src/node/index.ts
  packages/shared/src/node/logger/Logger.ts
  packages/shared/src/node/modules/app/data-access/data-access-app.ts
  packages/shared/src/node/modules/app/service/app-data-service.ts
  packages/shared/tsconfig.json
  packages/worker/.eslintrc.js
  packages/worker/package.json
  packages/worker/src/config/docker-templates.ts
  packages/worker/src/lib/docker/builders/schemas.ts
  packages/worker/src/lib/docker/builders/service-builder.ts
  packages/worker/src/lib/docker/docker-helpers.ts
  packages/worker/src/lib/socket/SocketManager.ts
  pnpm-lock.yaml
  src/app/(dashboard)/app-store/[id]/page.tsx
  src/app/(dashboard)/app-store/page.tsx
  src/app/(dashboard)/apps/page.tsx
  src/app/(dashboard)/layout.tsx
  src/app/actions/app-actions/update-all-apps-action.ts
  src/app/api/app-store/route.ts
  src/app/global-error.tsx
  src/app/page.tsx
  src/client/messages/en.json
  src/server/services/app-catalog/app-catalog-cache.ts
  src/server/services/app-catalog/app-catalog.service.test.ts
  src/server/services/app-catalog/app-catalog.service.ts
  src/server/services/app-catalog/apps.helpers.test.ts
  src/server/services/app-catalog/apps.helpers.ts
  src/server/services/app-catalog/commands/get-app-command.ts
  src/server/services/app-catalog/commands/get-guest-dashboard-apps-command.ts
  src/server/services/app-catalog/commands/get-installed-apps-command.ts
  src/server/services/app-catalog/commands/list-apps-command.ts
  src/server/services/app-catalog/commands/search-apps-command.ts
  src/server/services/app-catalog/commands/types.ts
  src/server/services/app-lifecycle/app-lifecycle.service.test.ts
  src/server/services/app-lifecycle/app-lifecycle.service.ts
  src/server/services/app-lifecycle/commands/__tests__/install-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/reset-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/restart-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/start-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/stop-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/uninstall-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/update-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/update-app-config-command.test.ts
  src/server/services/app-lifecycle/commands/install-app-command.ts
  src/server/services/app-lifecycle/commands/types.ts
  src/server/services/app-lifecycle/commands/uninstall-app-command.ts
  src/server/services/app-lifecycle/commands/update-app-command.ts
  src/server/services/app-lifecycle/commands/update-app-config-command.ts
  vitest.workspace.ts
Labels: size/XXL

#1494 refactor(app-status): move to provider and client state
  packages/shared/src/schemas/socket-schemas.ts
  packages/worker/src/services/app/app.executors.ts
  src/app/(dashboard)/app-store/[id]/components/AppDetailsContainer/AppDetailsContainer.tsx
  src/app/(dashboard)/app-store/[id]/components/AppDetailsContainer/AppDetailsWrapper.tsx
  src/app/(dashboard)/app-store/[id]/components/AppDetailsContainer/index.ts
  src/app/(dashboard)/app-store/[id]/page.tsx
  src/app/(dashboard)/apps/page.tsx
  src/app/components/ClientProviders/AppStatusProvider/app-status-provider.tsx
  src/app/components/ClientProviders/AppStatusProvider/app-status-store.ts
  src/app/components/ClientProviders/ClientProviders.tsx
  src/app/components/ClientProviders/SocketProvider/SocketProvider.ts
  src/app/components/GuestDashboardApps/GuestDashboardApps.tsx
  src/app/layout.tsx
  src/client/components/AppTile/AppTile.tsx
Labels: size/L

#1499 chore: bump pnpm
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
Labels: size/XS

#1501 refactor(app-details): move client components down
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/(dashboard)/app-store/[id]/components/AppActions/AppActions.test.tsx
  src/app/(dashboard)/app-store/[id]/components/AppActions/AppActions.tsx
  src/app/(dashboard)/app-store/[id]/components/AppDetailsContainer/AppDetailsContainer.tsx
  src/app/(dashboard)/app-store/[id]/components/AppDetailsTabs/AppDetailsTabs.tsx
  src/app/(dashboard)/app-store/[id]/components/InstallModal/InstallModal.test.tsx
  src/app/(dashboard)/app-store/[id]/components/InstallModal/InstallModal.tsx
  src/app/(dashboard)/app-store/[id]/components/ResetAppModal/ResetAppModal.tsx
  src/app/(dashboard)/app-store/[id]/components/RestartModal/RestartModal.tsx
  src/app/(dashboard)/app-store/[id]/components/StopModal/StopModal.tsx
  src/app/(dashboard)/app-store/[id]/components/UninstallModal/UninstallModal.tsx
  src/app/(dashboard)/app-store/[id]/components/UpdateModal/UpdateModal.test.tsx
  src/app/(dashboard)/app-store/[id]/components/UpdateModal/UpdateModal.tsx
  src/app/(dashboard)/app-store/[id]/components/UpdateSettingsModal/UpdateSettingsModal.tsx
  src/app/(dashboard)/app-store/[id]/page.tsx
  src/app/layout.tsx
  src/client/components/AppStatus/AppStatus.tsx
  src/client/components/AppTile/AppTile.tsx
  src/i18n.ts
  tests/test-utils.tsx
  tsconfig.json
Labels: size/XXL

#1490 New Crowdin updates
  src/client/messages/af-ZA.json
  src/client/messages/ar-SA.json
  src/client/messages/ca-ES.json
  src/client/messages/cs-CZ.json
  src/client/messages/da-DK.json
  src/client/messages/de-DE.json
  src/client/messages/el-GR.json
  src/client/messages/en-US.json
  src/client/messages/es-ES.json
  src/client/messages/fi-FI.json
  src/client/messages/fr-FR.json
  src/client/messages/he-IL.json
  src/client/messages/hu-HU.json
  src/client/messages/it-IT.json
  src/client/messages/ja-JP.json
  src/client/messages/ko-KR.json
  src/client/messages/nl-NL.json
  src/client/messages/no-NO.json
  src/client/messages/pl-PL.json
  src/client/messages/pt-BR.json
  src/client/messages/pt-PT.json
  src/client/messages/ro-RO.json
  src/client/messages/ru-RU.json
  src/client/messages/sr-SP.json
  src/client/messages/sv-SE.json
  src/client/messages/tr-TR.json
  src/client/messages/uk-UA.json
  src/client/messages/vi-VN.json
  src/client/messages/zh-CN.json
  src/client/messages/zh-TW.json
Labels: size/M

#1505 feat: introduce table and pagination components
  package.json
  pnpm-lock.yaml
  src/app/(auth)/login/components/LoginForm/LoginForm.tsx
  src/app/(auth)/register/components/RegisterForm/RegisterForm.tsx
  src/app/(auth)/reset-password/components/ResetPasswordContainer/ResetPasswordContainer.tsx
  src/app/(auth)/reset-password/components/ResetPasswordForm/ResetPasswordForm.tsx
  src/app/(dashboard)/app-store/[id]/components/AppActions/AppActions.module.scss
  src/app/(dashboard)/app-store/[id]/components/AppActions/AppActions.tsx
  src/app/(dashboard)/app-store/[id]/components/InstallForm/InstallForm.tsx
  src/app/(dashboard)/app-store/[id]/components/ResetAppModal/ResetAppModal.tsx
  src/app/(dashboard)/app-store/[id]/components/RestartModal/RestartModal.tsx
  src/app/(dashboard)/app-store/[id]/components/StopModal/StopModal.tsx
  src/app/(dashboard)/app-store/[id]/components/UninstallModal/UninstallModal.tsx
  src/app/(dashboard)/app-store/[id]/components/UpdateModal/UpdateModal.tsx
  src/app/(dashboard)/apps/components/UpdateAllButton/UpdateAllButton.tsx
  src/app/(dashboard)/apps/components/UpdateAllModal/UpdateAllModal.tsx
  src/app/(dashboard)/components/AddLink/AddLinkModal.tsx
  src/app/(dashboard)/components/AddLink/DeleteLinkModal.tsx
  src/app/(dashboard)/components/Welcome/Welcome.tsx
  src/app/(dashboard)/settings/components/ChangeUsernameForm/ChangeUsernameForm.tsx
  src/app/(dashboard)/settings/components/OtpForm/OtpForm.tsx
  src/app/(dashboard)/settings/components/SettingsForm/SettingsForm.tsx
  src/app/components/EmptyPage/EmptyPage.tsx
  src/client/components/StatusScreen/StatusScreen.tsx
  src/client/components/ui/Button/Button.test.tsx
  src/client/components/ui/Button/Button.tsx
  src/client/components/ui/Button/index.ts
  src/client/components/ui/EmptyPage/EmptyPage.tsx
  src/client/components/ui/ErrorPage/ErrorPage.tsx
  src/client/components/ui/Pagination/Pagination.tsx
  src/client/components/ui/Table/Table.tsx
  src/client/components/ui/Table/index.ts
Labels: size/L
