Repository runtipi/runtipi, pull requests merged in 2024-08, with the labels that each got.

#1568 fix(backups): use streaming to allow large files backups
  packages/shared/src/schemas/queue-schemas.ts
  packages/worker/package.json
  packages/worker/src/api.ts
  packages/worker/src/index.ts
  packages/worker/src/lib/archive/ArchiveManager.ts
  packages/worker/src/services/app/__tests__/app.executors.test.ts
  packages/worker/src/services/app/app.executors.ts
  packages/worker/src/watcher/watcher.ts
  pnpm-lock.yaml
  src/app/(dashboard)/app-store/[id]/components/UpdateModal/UpdateModal.tsx
  src/app/actions/app-actions/update-all-apps-action.ts
  src/app/actions/app-actions/update-app-action.ts
  src/client/messages/en.json
  src/server/core/EventDispatcher/EventDispatcher.ts
  src/server/services/app-backup/commands/create-app-backup-command.ts
  src/server/services/app-lifecycle/commands/__tests__/update-app-command.test.ts
  src/server/services/app-lifecycle/commands/update-app-command.ts
Labels: size/L

#1573 Sync master to develop
  package.json
  src/server/services/app-lifecycle/commands/update-app-command.ts
Labels: size/XS

#1575 chore: setup biomejs and correct a few files
  .prettierignore
  .prettierrc.js
  biome.json
  package.json
  packages/shared/src/helpers/env-helpers.ts
  packages/shared/src/helpers/error-helpers.ts
  packages/worker/src/services/repo/repo.executors.ts
  packages/worker/src/services/repo/repo.helpers.ts
  packages/worker/tests/vite.setup.ts
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/inversify.config.ts
  src/server/tests/apps.factory.ts
Labels: size/L

#1579 chore(sentry): avoid sending errors related to custom user configs
  packages/shared/src/helpers/error-helpers.ts
  packages/worker/src/lib/docker/docker-helpers.ts
  packages/worker/src/lib/system/system.helpers.ts
  sentry.client.config.ts
  src/instrumentation.ts
Labels: size/L

#1572 New Crowdin updates
  src/client/messages/af-ZA.json
  src/client/messages/ar-SA.json
  src/client/messages/ca-ES.json
  src/client/messages/cs-CZ.json
  src/client/messages/da-DK.json
  src/client/messages/de-DE.json
  src/client/messages/el-GR.json
  src/client/messages/en-US.json
  src/client/messages/es-ES.json
  src/client/messages/fi-FI.json
  src/client/messages/fr-FR.json
  src/client/messages/he-IL.json
  src/client/messages/hu-HU.json
  src/client/messages/it-IT.json
  src/client/messages/ja-JP.json
  src/client/messages/ko-KR.json
  src/client/messages/nl-NL.json
  src/client/messages/no-NO.json
  src/client/messages/pl-PL.json
  src/client/messages/pt-BR.json
  src/client/messages/pt-PT.json
  src/client/messages/ro-RO.json
  src/client/messages/ru-RU.json
  src/client/messages/sr-SP.json
  src/client/messages/sv-SE.json
  src/client/messages/tr-TR.json
  src/client/messages/uk-UA.json
  src/client/messages/vi-VN.json
  src/client/messages/zh-CN.json
  src/client/messages/zh-TW.json
Labels: size/L

#1583 feat(backups): disable in demo mode
  src/server/services/app-backup/commands/create-app-backup-command.ts
Labels: size/XS

#1593 feat: new app label
  packages/shared/src/node/modules/app/service/app-data-service.ts
  packages/shared/src/schemas/app-schemas.ts
  src/app/(dashboard)/app-store/components/AppStoreTile/AppStoreTile.tsx
  src/server/services/app-catalog/app-catalog-cache.ts
  src/server/tests/apps.factory.ts
Labels: size/S

#1590 Support log coloring
  package.json
  packages/worker/package.json
  packages/worker/src/lib/docker/docker-helpers.ts
  pnpm-lock.yaml
  src/app/components/LogsTerminal/LogsTerminal.tsx
Labels: size/L

#1475 feat(worker): add support for docker-compose.arm64.json files
  packages/shared/src/schemas/env-schemas.ts
  packages/worker/src/lib/docker/docker-helpers.ts
  packages/worker/src/services/app/app.executors.ts
  src/server/services/app-catalog/app-catalog.service.test.ts
  src/server/services/app-lifecycle/commands/__tests__/install-app-command.test.ts
Labels: size/M

#1596 New Crowdin updates
  src/client/messages/uk-UA.json
Labels: size/XS

#1597 refactor: fix all biome issues in the codebase
  .github/workflows/ci.yml
  e2e/0004-user-settings.spec.ts
  e2e/helpers/settings.ts
  packages/shared/src/node/helpers/exec-async.tsx
  packages/shared/src/node/helpers/fs-helpers.ts
  packages/shared/src/node/logger/FileLogger.ts
  packages/shared/src/node/logger/Logger.ts
  packages/shared/src/node/modules/app/data-access/data-access-app.ts
  packages/worker/src/lib/archive/ArchiveManager.ts
  packages/worker/src/lib/docker/builders/docker-compose-builder.ts
  packages/worker/src/lib/docker/builders/service-builder.ts
  packages/worker/src/lib/docker/docker-helpers.test.ts
  packages/worker/src/lib/docker/docker-helpers.ts
  packages/worker/src/lib/system/system.helpers.test.ts
  packages/worker/src/lib/system/system.helpers.ts
  packages/worker/src/services/app/__tests__/app.helpers.test.ts
  packages/worker/src/services/app/app.helpers.ts
  packages/worker/src/services/app/env.helpers.ts
  packages/worker/src/services/system/system.executors.ts
  packages/worker/tests/apps.factory.ts
  packages/worker/tests/mocks/fs.ts
  src/app/(dashboard)/app-store/[id]/components/InstallForm/InstallFormField.tsx
  src/app/(dashboard)/app-store/[id]/utils/validators/validators.ts
  src/app/(dashboard)/components/AddLink/AddLinkButton.tsx
  src/app/(dashboard)/components/Header/Header.tsx
  src/app/(dashboard)/settings/components/SettingsForm/SettingsForm.tsx
  src/app/api/app-image/route.ts
  src/app/components/LogsTerminal/LogsTerminal.tsx
  src/app/components/TablePagination/TablePagination.tsx
  src/app/hooks/useAppStatus.tsx
  src/app/hooks/useClientSettings.tsx
  src/client/components/AppLogo/AppLogo.tsx
  src/client/components/FileSize/FileSize.tsx
  src/client/components/ui/OtpInput/OtpInput.test.tsx
  src/client/components/ui/OtpInput/OtpInput.tsx
  src/client/components/ui/ScrollArea/ScrollArea.tsx
  src/i18n.ts
  src/lib/socket/useSocket.ts
  src/server/core/Logger/Logger.ts
  src/server/core/TipiConfig/TipiConfig.test.ts
  src/server/services/app-catalog/app-catalog-cache.ts
  src/server/utils/encryption.ts
  src/server/utils/network.ts
  tests/mocks/fs.ts
Labels: size/L

#1603 refactor: isolate cache in its own package
  Dockerfile
  Dockerfile.dev
  biome.json
  package.json
  packages/cache/package.json
  packages/cache/src/cache.ts
  packages/cache/src/index.ts
  packages/cache/src/mock.ts
  packages/cache/tsconfig.json
  packages/worker/package.json
  packages/worker/src/index.ts
  packages/worker/src/inversify.config.ts
  packages/worker/src/watcher/watcher.ts
  packages/worker/tests/vite.setup.ts
  pnpm-lock.yaml
  src/app/(auth)/login/page.tsx
  src/app/(auth)/register/page.tsx
  src/app/(dashboard)/apps/page.tsx
  src/app/(dashboard)/layout.tsx
  src/app/(dashboard)/settings/page.tsx
  src/app/actions/acknowledge-welcome/acknowledge-welcome.ts
  src/app/actions/utils/ensure-user.ts
  src/app/api/certificate/route.ts
  src/app/page.tsx
  src/inversify.config.ts
  src/server/common/session-manager.ts
  src/server/common/session.helpers.ts
  src/server/queries/auth/auth.queries.ts
  src/server/run-migrations-dev.ts
  src/server/services/auth/auth.service.test.ts
  src/server/services/auth/auth.service.ts
  src/server/services/system/index.ts
  src/server/services/system/system.service.test.ts
  src/server/services/system/system.service.ts
  src/server/tests/drizzle-helpers.ts
  src/server/tests/test-utils.ts
  src/server/tests/user.factory.ts
  tests/mocks/drizzle.ts
  tests/mocks/redis.ts
  tests/server/test.setup.ts
Labels: size/XXL

#1606 New Crowdin updates
  src/client/messages/de-DE.json
Labels: size/M

#1609 New Crowdin updates
  src/client/messages/fr-FR.json
Labels: size/XS

#1612 fix: socket not working whith custom port
  docker-compose.dev.yml
  src/lib/socket/useSocket.ts
Labels: size/XS

#1615 New Crowdin updates
  src/client/messages/sv-SE.json
  src/client/messages/uk-UA.json
Labels: size/M

#1617 Release/3.5.3
  biome.json
  packages/worker/src/services/system/system.executors.ts
  src/app/(dashboard)/apps/page.tsx
  src/server/queries/apps/apps.queries.ts
Labels: size/S

#1620 Sort backup list newest -> oldest
  packages/shared/src/node/modules/app/data-access/data-access-app.ts
  packages/shared/src/node/modules/app/service/app-data-service.ts
  src/app/(dashboard)/app-store/[id]/components/AppDetailsTabs/AppBackups.tsx
Labels: size/XS

#1631 feat(docker-json): make internal port optional, add extra_hosts, network_mode and ulimits
  packages/worker/src/config/__tests__/docker-templates.test.ts
  packages/worker/src/config/docker-templates.ts
  packages/worker/src/config/index.ts
  packages/worker/src/lib/docker/builders/schemas.ts
  packages/worker/src/lib/docker/builders/service-builder.ts
  packages/worker/src/lib/docker/index.ts
Labels: size/L

#1633 feat: add support for base64 random values
  packages/shared/src/helpers/env-helpers.ts
  packages/shared/src/schemas/app-schemas.ts
  packages/worker/src/lib/docker/builders/service-builder.ts
  packages/worker/src/services/app/__tests__/env.helpers.test.ts
  packages/worker/src/services/app/app.helpers.ts
  packages/worker/src/services/app/env.helpers.ts
Labels: size/L

#1625 New Crowdin updates
  src/client/messages/uk-UA.json
Labels: size/XS

#1632 Feat/pull repo button
  packages/worker/src/watcher/watcher.ts
  src/app/(dashboard)/app-store/[id]/components/AppActions/AppActions.test.tsx
  src/app/(dashboard)/app-store/[id]/components/AppActions/AppActions.tsx
  src/app/(dashboard)/app-store/[id]/components/AppDetailsContainer/AppDetailsContainer.tsx
  src/app/(dashboard)/app-store/[id]/page.tsx
  src/app/(dashboard)/app-store/page.tsx
  src/app/(dashboard)/apps/page.tsx
  src/app/(dashboard)/layout.tsx
  src/app/(dashboard)/settings/components/GeneralActions/GeneralActions.tsx
  src/app/(dashboard)/settings/components/GeneralActions/components/UpdateRepoModal/UpateRepoModal.tsx
  src/app/(dashboard)/settings/components/GeneralActions/index.ts
  src/app/(dashboard)/settings/components/SettingsForm/SettingsForm.tsx
  src/app/actions/app-actions/update-all-apps-action.ts
  src/app/actions/settings/update-repo-action.ts
  src/app/api/app-store/route.ts
  src/app/components/GuestDashboardApps/GuestDashboardApps.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/client/messages/en.json
  src/inversify.config.ts
  src/server/services/app-catalog/app-catalog-cache.ts
  src/server/services/app-catalog/app-catalog.service.test.ts
  src/server/services/app-catalog/app-catalog.service.ts
  src/server/services/app-catalog/commands/get-app-command.ts
  src/server/services/app-catalog/commands/get-guest-dashboard-apps-command.ts
  src/server/services/app-catalog/commands/get-installed-apps-command.ts
  src/server/services/app-catalog/commands/index.ts
  src/server/services/app-catalog/commands/list-apps-command.ts
  src/server/services/app-catalog/commands/search-apps-command.ts
  src/server/services/app-catalog/commands/types.ts
  src/server/services/system/system.service.test.ts
  src/server/services/system/system.service.ts
  src/server/tests/apps.factory.ts
Labels: size/XL

#1636 Release/v3.6.0
  Dockerfile.dev
  biome.json
  package.json
  packages/shared/src/helpers/env-helpers.ts
  packages/shared/src/node/modules/app/data-access/data-access-app.ts
  packages/shared/src/node/modules/app/service/app-data-service.ts
  packages/shared/src/schemas/app-schemas.ts
  packages/shared/src/schemas/queue-schemas.ts
  packages/worker/package.json
  packages/worker/src/config/__tests__/docker-templates.test.ts
  packages/worker/src/config/docker-templates.ts
  packages/worker/src/config/index.ts
  packages/worker/src/index.ts
  packages/worker/src/lib/docker/builders/schemas.ts
  packages/worker/src/lib/docker/builders/service-builder.ts
  packages/worker/src/lib/docker/index.ts
  packages/worker/src/lib/system/system.helpers.ts
  packages/worker/src/services/app/__tests__/env.helpers.test.ts
  packages/worker/src/services/app/app.executors.ts
  packages/worker/src/services/app/app.helpers.ts
  packages/worker/src/services/app/env.helpers.ts
  packages/worker/src/watcher/watcher.ts
  pnpm-lock.yaml
  src/app/(dashboard)/app-store/[id]/components/AppActions/AppActions.test.tsx
  src/app/(dashboard)/app-store/[id]/components/AppActions/AppActions.tsx
  src/app/(dashboard)/app-store/[id]/components/AppDetailsContainer/AppDetailsContainer.tsx
  src/app/(dashboard)/app-store/[id]/components/AppDetailsTabs/AppBackups.tsx
  src/app/(dashboard)/app-store/[id]/page.tsx
  src/app/(dashboard)/app-store/page.tsx
  src/app/(dashboard)/apps/page.tsx
  src/app/(dashboard)/layout.tsx
  src/app/(dashboard)/settings/components/GeneralActions/GeneralActions.tsx
  src/app/(dashboard)/settings/components/GeneralActions/components/UpdateRepoModal/UpateRepoModal.tsx
  src/app/(dashboard)/settings/components/GeneralActions/index.ts
  src/app/(dashboard)/settings/components/SettingsForm/SettingsForm.tsx
  src/app/actions/app-actions/update-all-apps-action.ts
  src/app/actions/settings/update-repo-action.ts
  src/app/api/app-store/route.ts
  src/app/components/GuestDashboardApps/GuestDashboardApps.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/client/messages/en.json
  src/client/messages/uk-UA.json
  src/inversify.config.ts
  src/server/services/app-catalog/app-catalog-cache.ts
  src/server/services/app-catalog/app-catalog.service.test.ts
  src/server/services/app-catalog/app-catalog.service.ts
  src/server/services/app-catalog/commands/get-app-command.ts
  src/server/services/app-catalog/commands/get-guest-dashboard-apps-command.ts
  src/server/services/app-catalog/commands/get-installed-apps-command.ts
  src/server/services/app-catalog/commands/index.ts
  src/server/services/app-catalog/commands/list-apps-command.ts
  src/server/services/app-catalog/commands/search-apps-command.ts
  src/server/services/app-catalog/commands/types.ts
  src/server/services/system/system.service.test.ts
  src/server/services/system/system.service.ts
  src/server/tests/apps.factory.ts
Labels: size/XXL

#1641 docs(README): add coderabbit as a sponsor
  README.md
  screenshots/sponsors/coderabbit.png
Labels: size/S

#1642 chore: docs update sponsor logo size
  README.md
Labels: size/XS
