Repository runtipi/runtipi, pull requests merged in 2024-09, with the labels that each got.

#1657 fix(app-store): limit the file reading to 10 items in parallel
  packages/shared/src/helpers/utils.ts
  packages/shared/src/node/modules/app/service/app-data-service.ts
  src/server/services/app-lifecycle/app-lifecycle.service.test.ts
  src/server/services/app-lifecycle/commands/__tests__/install-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/reset-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/restart-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/start-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/stop-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/uninstall-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/update-app-command.test.ts
Labels: size/M

#1665 add translation support for strings in app backup section
  src/app/(dashboard)/app-store/[id]/components/AppDetailsTabs/AppBackups.tsx
  src/app/(dashboard)/apps/components/UpdateAllButton/UpdateAllButton.tsx
Labels: size/XS

#1671 fix(docker): use compose json from local folder
  packages/shared/package.json
  packages/shared/src/node/index.ts
  packages/shared/src/node/modules/app/__tests__/app-file-accessor.test.ts
  packages/shared/src/node/modules/app/app-data-service.ts
  packages/shared/src/node/modules/app/app-file-accessor.ts
  packages/shared/src/node/modules/app/data-access/data-access-app.ts
  packages/shared/src/node/modules/app/service/app-data-service.ts
  packages/shared/src/node/modules/archive/archive-manager.ts
  packages/shared/src/node/modules/backup/backup-manager.ts
  packages/worker/package.json
  packages/worker/src/inversify.config.ts
  packages/worker/src/lib/environment/environment.ts
  packages/worker/src/services/app/__tests__/app.helpers.test.ts
  packages/worker/src/services/app/app.executors.ts
  packages/worker/src/services/app/app.helpers.ts
  pnpm-lock.yaml
  src/inversify.config.ts
  src/server/services/app-backup/app-backup.service.ts
  src/server/services/app-backup/commands/delete-app-backup-command.ts
  src/server/services/app-backup/commands/get-app-backups-command.ts
  src/server/services/app-backup/commands/types.ts
  src/server/services/app-catalog/app-catalog.service.test.ts
  src/server/services/app-catalog/app-catalog.service.ts
  src/server/services/app-lifecycle/app-lifecycle.service.test.ts
  src/server/services/app-lifecycle/app-lifecycle.service.ts
  src/server/services/app-lifecycle/commands/__tests__/install-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/reset-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/restart-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/start-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/stop-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/uninstall-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/update-app-command.test.ts
  src/server/services/app-lifecycle/commands/__tests__/update-app-config-command.test.ts
  src/server/services/app-lifecycle/commands/install-app-command.ts
  src/server/services/app-lifecycle/commands/types.ts
  src/server/services/app-lifecycle/commands/update-app-command.ts
  src/server/services/app-lifecycle/commands/update-app-config-command.ts
Labels: size/XXL

#1685 Added new `interface` key to ports in the dynamic compose
  packages/worker/src/config/__tests__/docker-templates.test.ts
  packages/worker/src/lib/docker/builders/schemas.ts
  packages/worker/src/lib/docker/builders/service-builder.ts
Labels: size/S

#1634 New Crowdin updates
  src/client/messages/af-ZA.json
  src/client/messages/ar-SA.json
  src/client/messages/ca-ES.json
  src/client/messages/cs-CZ.json
  src/client/messages/da-DK.json
  src/client/messages/de-DE.json
  src/client/messages/el-GR.json
  src/client/messages/en-US.json
  src/client/messages/es-ES.json
  src/client/messages/fi-FI.json
  src/client/messages/fr-FR.json
  src/client/messages/he-IL.json
  src/client/messages/hu-HU.json
  src/client/messages/it-IT.json
  src/client/messages/ja-JP.json
  src/client/messages/ko-KR.json
  src/client/messages/nl-NL.json
  src/client/messages/no-NO.json
  src/client/messages/pl-PL.json
  src/client/messages/pt-BR.json
  src/client/messages/pt-PT.json
  src/client/messages/ro-RO.json
  src/client/messages/ru-RU.json
  src/client/messages/sr-SP.json
  src/client/messages/sv-SE.json
  src/client/messages/tr-TR.json
  src/client/messages/uk-UA.json
  src/client/messages/vi-VN.json
  src/client/messages/zh-CN.json
  src/client/messages/zh-TW.json
Labels: size/XL
