Repository runtipi/runtipi, pull requests merged in 2024-03, with the labels that each got.

#1158 Fix: added field type in InstallForm inputs
  src/app/(dashboard)/app-store/[id]/components/InstallForm/InstallForm.tsx
Labels: size/XS

#1280 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: size/XS

#1308 chore: add pi image builds on release workflows
  .github/workflows/beta-release.yml
  .github/workflows/release.yml
Labels: size/S

#1331 feat(app-store): implement infinite scroll instead of load more button
  src/app/(dashboard)/app-store/components/AppStoreTable/AppStoreTable.tsx
  src/app/(dashboard)/app-store/components/AppStoreTile/AppStoreTile.tsx
  src/client/hooks/useInfiniteScroll.ts
Labels: size/M

#1335 chore: update bug template to include custom docker compose file
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: size/S
