Repository runtipi/runtipi, pull requests merged in 2024-11, with the labels that each got.

#1741 New Crowdin updates
  src/client/messages/pt-PT.json
Labels: size/S

#1746 Release/3.6.4
  .all-contributorsrc
  .github/workflows/alpha-release.yml
  .github/workflows/beta-release.yml
  .github/workflows/issue-auto-close.yml
  Dockerfile
  README.md
  package.json
  packages/cache/package.json
  packages/db/package.json
  packages/shared/package.json
  packages/shared/src/index.ts
  packages/shared/src/schemas/queue-schemas.ts
  packages/worker/package.json
  packages/worker/src/services/app/app.executors.ts
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/client/messages/pt-PT.json
  src/server/services/app-lifecycle/commands/install-app-command.ts
  src/server/services/app-lifecycle/commands/reset-app-command.ts
  src/server/services/app-lifecycle/commands/restart-app-command.ts
  src/server/services/app-lifecycle/commands/start-app-command.ts
  src/server/services/app-lifecycle/commands/stop-app-command.ts
  src/server/services/app-lifecycle/commands/uninstall-app-command.ts
  src/server/services/app-lifecycle/commands/update-app-command.ts
  src/server/services/app-lifecycle/commands/update-app-config-command.ts
Labels: size/XXL

#1754 ci: fix-checks
  .github/workflows/ci.yml
  biome.json
  package.json
  packages/frontend/src/modules/app/components/dialogs/restore-app-dialog/restore-app-dialog.tsx
Labels: size/M

#1756 Add option to remove app backups when uninstalling
  packages/backend/src/metadata.ts
  packages/backend/src/modules/app-lifecycle/app-lifecycle.controller.ts
  packages/backend/src/modules/app-lifecycle/app-lifecycle.service.ts
  packages/backend/src/modules/app-lifecycle/dto/app-lifecycle.dto.ts
  packages/backend/src/modules/backups/backup.manager.ts
  packages/backend/src/modules/i18n/translations/en.json
  packages/backend/src/swagger.json
  packages/frontend/src/api-client/types.gen.ts
  packages/frontend/src/modules/app/components/dialogs/uninstall-dialog/uninstall-dialog.tsx
Labels: size/M

#1755 ci: fix releases
  .github/workflows/alpha-release.yml
  .github/workflows/beta-release.yml
  .github/workflows/e2e.yml
  .github/workflows/release.yml
  e2e/0005-guest-dashboard.spec.ts
  e2e/fixtures/fixtures.ts
  e2e/helpers/db.ts
  e2e/helpers/settings.ts
  package.json
  packages/backend/src/modules/apps/app-catalog.service.ts
  packages/frontend/src/components/header/header.tsx
  packages/frontend/src/modules/dashboard/pages/guest-dashboard.tsx
  playwright.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/install.sh
Labels: size/L

#1758 feat: update repo button
  packages/backend/src/metadata.ts
  packages/backend/src/modules/repos/dto/repos.dto.ts
  packages/backend/src/modules/repos/repos.controller.ts
  packages/backend/src/modules/repos/repos.module.ts
  packages/backend/src/swagger.json
  packages/frontend/src/api-client/@tanstack/react-query.gen.ts
  packages/frontend/src/api-client/schemas.gen.ts
  packages/frontend/src/api-client/services.gen.ts
  packages/frontend/src/api-client/types.gen.ts
  packages/frontend/src/modules/settings/components/update-repo-modal/update-repo-modal.tsx
  packages/frontend/src/modules/settings/containers/general-actions.tsx
Labels: size/L

#1764 Introducing Tipi Guru on Gurubase.io
  README.md
Labels: size/XS

#1769 feat: display tooltip on app tile description
  packages/frontend/src/modules/app/components/store-tile/store-tile.tsx
Labels: size/XS

#1777 New Crowdin updates
  packages/backend/src/modules/i18n/translations/af-ZA.json
  packages/backend/src/modules/i18n/translations/ar-SA.json
  packages/backend/src/modules/i18n/translations/ca-ES.json
  packages/backend/src/modules/i18n/translations/cs-CZ.json
  packages/backend/src/modules/i18n/translations/da-DK.json
  packages/backend/src/modules/i18n/translations/de-DE.json
  packages/backend/src/modules/i18n/translations/el-GR.json
  packages/backend/src/modules/i18n/translations/en-US.json
  packages/backend/src/modules/i18n/translations/es-ES.json
  packages/backend/src/modules/i18n/translations/fi-FI.json
  packages/backend/src/modules/i18n/translations/fr-FR.json
  packages/backend/src/modules/i18n/translations/he-IL.json
  packages/backend/src/modules/i18n/translations/hu-HU.json
  packages/backend/src/modules/i18n/translations/it-IT.json
  packages/backend/src/modules/i18n/translations/ja-JP.json
  packages/backend/src/modules/i18n/translations/ko-KR.json
  packages/backend/src/modules/i18n/translations/nl-NL.json
  packages/backend/src/modules/i18n/translations/no-NO.json
  packages/backend/src/modules/i18n/translations/pl-PL.json
  packages/backend/src/modules/i18n/translations/pt-BR.json
  packages/backend/src/modules/i18n/translations/pt-PT.json
  packages/backend/src/modules/i18n/translations/ro-RO.json
  packages/backend/src/modules/i18n/translations/ru-RU.json
  packages/backend/src/modules/i18n/translations/sr-SP.json
  packages/backend/src/modules/i18n/translations/sv-SE.json
  packages/backend/src/modules/i18n/translations/tr-TR.json
  packages/backend/src/modules/i18n/translations/uk-UA.json
  packages/backend/src/modules/i18n/translations/vi-VN.json
  packages/backend/src/modules/i18n/translations/zh-CN.json
  packages/backend/src/modules/i18n/translations/zh-TW.json
Labels: size/XXL

#1778 refactor: fix dialog titles and footers
  packages/frontend/src/components/ui/ScrollArea/ScrollArea.tsx
  packages/frontend/src/modules/app/components/dialogs/add-link/add-link-dialog.tsx
  packages/frontend/src/modules/app/components/dialogs/delete-link/delete-link-dialog.tsx
  packages/frontend/src/modules/app/components/dialogs/install-dialog/install-dialog.tsx
  packages/frontend/src/modules/app/components/dialogs/reset-dialog/reset-dialog.tsx
  packages/frontend/src/modules/app/components/dialogs/restart-dialog/restart-dialog.tsx
  packages/frontend/src/modules/app/components/dialogs/stop-dialog/stop-dialog.tsx
  packages/frontend/src/modules/app/components/dialogs/uninstall-dialog/uninstall-dialog.tsx
  packages/frontend/src/modules/app/components/dialogs/update-dialog/update-dialog.tsx
  packages/frontend/src/modules/app/components/dialogs/update-settings-dialog/update-settings-dialog.tsx
  packages/frontend/src/modules/app/components/install-form-buttons/install-form-buttons.tsx
  packages/frontend/src/modules/app/components/install-form/install-form.tsx
  packages/frontend/src/modules/app/components/update-all-button/update-all-button.tsx
  packages/frontend/src/modules/settings/components/change-username-form/change-username-form.tsx
  packages/frontend/src/modules/settings/components/otp-form/otp-form.tsx
Labels: size/L

#1782 fix: include previous settings when writing settings file
  packages/backend/src/core/config/configuration.service.ts
  packages/backend/src/core/filesystem/filesystem.service.ts
Labels: size/S

#1783 New Crowdin updates
  packages/backend/src/modules/i18n/translations/uk-UA.json
Labels: size/XS

#1795 fix(errors): send intl params if server throws translatable error
  packages/backend/src/common/error/exception.filter.ts
  packages/backend/src/modules/app-lifecycle/app-lifecycle.service.ts
  packages/backend/src/modules/app-lifecycle/commands/command.ts
  packages/frontend/src/components/providers/location-listener/location-listener.tsx
  packages/frontend/src/modules/app/containers/app-actions/app-actions.tsx
Labels: size/S

#1796 fix: return res when passthrough is not true
  packages/backend/src/modules/apps/apps.controller.ts
  packages/backend/src/modules/auth/auth.controller.ts
  packages/backend/src/modules/system/system.controller.ts
Labels: size/S

#1806 fix(frontend): fix tabler icons load of all icons
  packages/frontend/vite.config.ts
Labels: size/XS

#1805 fix: add back previous migrations as custom drizzle ones
  packages/backend/package.json
  packages/backend/src/core/database/drizzle/0002_add-app-version.sql
  packages/backend/src/core/database/drizzle/0003_add-status-updating.sql
  packages/backend/src/core/database/drizzle/0004_add-exposed-domain-fields.sql
  packages/backend/src/core/database/drizzle/0005_add-user-operator.sql
  packages/backend/src/core/database/drizzle/0006_add-totp-user-fields.sql
  packages/backend/src/core/database/drizzle/0007_merge-config-with-domain-and-exposed.sql
  packages/backend/src/core/database/drizzle/0008_add-guest-dashboard.sql
  packages/backend/src/core/database/drizzle/0009_add-status-resetting.sql
  packages/backend/src/core/database/drizzle/0010_link-table-description.sql
  packages/backend/src/core/database/drizzle/0011_app-local-exposed.sql
  packages/backend/src/core/database/drizzle/0012_restarting-state.sql
  packages/backend/src/core/database/drizzle/0013_backingup-state.sql
  packages/backend/src/core/database/drizzle/meta/0002_snapshot.json
  packages/backend/src/core/database/drizzle/meta/0003_snapshot.json
  packages/backend/src/core/database/drizzle/meta/0004_snapshot.json
  packages/backend/src/core/database/drizzle/meta/0005_snapshot.json
  packages/backend/src/core/database/drizzle/meta/0006_snapshot.json
  packages/backend/src/core/database/drizzle/meta/0007_snapshot.json
  packages/backend/src/core/database/drizzle/meta/0008_snapshot.json
  packages/backend/src/core/database/drizzle/meta/0009_snapshot.json
  packages/backend/src/core/database/drizzle/meta/0010_snapshot.json
  packages/backend/src/core/database/drizzle/meta/0011_snapshot.json
  packages/backend/src/core/database/drizzle/meta/0012_snapshot.json
  packages/backend/src/core/database/drizzle/meta/0013_snapshot.json
  packages/backend/src/core/database/drizzle/meta/_journal.json
Labels: size/XXL

#1785 New Crowdin updates
  packages/backend/src/modules/i18n/translations/hu-HU.json
  packages/backend/src/modules/i18n/translations/ko-KR.json
  packages/backend/src/modules/i18n/translations/pt-BR.json
  packages/backend/src/modules/i18n/translations/sv-SE.json
Labels: size/L
