Repository runtipi/runtipi, pull requests merged in 2024-07, with the labels that each got.

#1510 feat: Add server actions - component flow diagram to Readme
  README.md
Labels: size/XS

#1504 New Crowdin updates
  src/client/messages/fr-FR.json
  src/client/messages/pt-BR.json
  src/client/messages/sv-SE.json
  src/client/messages/uk-UA.json
  src/client/messages/zh-TW.json
Labels: size/XL

#1522 New Crowdin updates
  src/client/messages/fr-FR.json
  src/client/messages/pl-PL.json
Labels: size/M

#1535 refactor(client-settings): initialize in a zustand store on the server
  src/app/(dashboard)/app-store/[id]/components/AppActions/AppActions.test.tsx
  src/app/(dashboard)/app-store/[id]/components/AppActions/AppActions.tsx
  src/app/(dashboard)/app-store/[id]/components/AppDetailsTabs/AppDetailsTabs.tsx
  src/app/(dashboard)/app-store/[id]/components/InstallForm/InstallForm.test.tsx
  src/app/(dashboard)/app-store/[id]/components/InstallForm/InstallForm.tsx
  src/app/(dashboard)/app-store/[id]/components/InstallModal/InstallModal.tsx
  src/app/(dashboard)/app-store/[id]/components/ResetAppModal/ResetAppModal.tsx
  src/app/(dashboard)/app-store/[id]/components/RestartModal/RestartModal.tsx
  src/app/(dashboard)/app-store/[id]/components/StopModal/StopModal.tsx
  src/app/(dashboard)/app-store/[id]/components/UninstallModal/UninstallModal.tsx
  src/app/(dashboard)/app-store/[id]/components/UpdateModal/UpdateModal.tsx
  src/app/(dashboard)/components/Header/Header.tsx
  src/app/components/ClientProviders/AppStatusProvider/app-status-provider.tsx
  src/app/components/ClientProviders/ClientProviders.tsx
  src/app/components/ClientProviders/ClientSettingsProvider/ClientSettingsProvider.tsx
  src/app/components/ClientProviders/ClientSettingsProvider/client-settings-store.tsx
  src/app/components/ClientProviders/SocketProvider/SocketProvider.ts
  src/app/components/ClientProviders/ThemeProvider/ThemeProvider.tsx
  src/app/hooks/use-client-settings.ts
  src/app/hooks/useAppStatus.tsx
  src/app/hooks/useClientSettings.tsx
  src/app/layout.tsx
  src/client/components/AppStatus/AppStatus.tsx
  tests/test-utils.tsx
Labels: size/L

#1536 feat(settings): control timezone from settings ui
  .env.example
  docker-compose.dev.yml
  docker-compose.prod.yml
  package.json
  packages/shared/src/schemas/env-schemas.ts
  packages/worker/src/lib/system/system.helpers.ts
  pnpm-lock.yaml
  src/app/(dashboard)/settings/components/SettingsForm/SettingsForm.tsx
  src/app/components/TimeZoneSelector/TimeZoneSelector.tsx
  src/client/messages/en.json
  src/server/core/TipiConfig/TipiConfig.ts
Labels: size/L

#1537 New Crowdin updates
  src/client/messages/af-ZA.json
  src/client/messages/ar-SA.json
  src/client/messages/ca-ES.json
  src/client/messages/cs-CZ.json
  src/client/messages/da-DK.json
  src/client/messages/de-DE.json
  src/client/messages/el-GR.json
  src/client/messages/en-US.json
  src/client/messages/es-ES.json
  src/client/messages/fi-FI.json
  src/client/messages/fr-FR.json
  src/client/messages/he-IL.json
  src/client/messages/hu-HU.json
  src/client/messages/it-IT.json
  src/client/messages/ja-JP.json
  src/client/messages/ko-KR.json
  src/client/messages/nl-NL.json
  src/client/messages/no-NO.json
  src/client/messages/pl-PL.json
  src/client/messages/pt-BR.json
  src/client/messages/pt-PT.json
  src/client/messages/ro-RO.json
  src/client/messages/ru-RU.json
  src/client/messages/sr-SP.json
  src/client/messages/sv-SE.json
  src/client/messages/tr-TR.json
  src/client/messages/uk-UA.json
  src/client/messages/vi-VN.json
  src/client/messages/zh-CN.json
  src/client/messages/zh-TW.json
Labels: size/XXL

#1545 refactor: introduce DI with inversify
  package.json
  packages/shared/src/node/index.ts
  packages/shared/src/node/logger/FileLogger.ts
  packages/shared/src/node/logger/Logger.interface.ts
  packages/shared/src/node/logger/Logger.ts
  packages/shared/src/node/modules/app/data-access/data-access-app.ts
  packages/worker/package.json
  packages/worker/src/index.ts
  packages/worker/src/inversify.config.ts
  packages/worker/src/lib/logger/logger.ts
  packages/worker/src/lib/socket/SocketManager.ts
  packages/worker/src/lib/socket/index.ts
  packages/worker/src/services/app/app.executors.ts
  packages/worker/tsconfig.json
  pnpm-lock.yaml
  src/inversify.config.ts
  src/server/core/TipiCache/TipiCache.ts
  src/server/core/TipiCache/index.ts
  src/server/services/app-catalog/app-catalog-cache.ts
  src/server/services/auth/auth.service.ts
  src/server/services/system/system.service.test.ts
  tsconfig.json
Labels: size/L
