Repository runtipi/runtipi, pull requests merged in 2024-02, with the labels that each got.

#1206 feat: add custom links
  .dockerignore
  package.json
  packages/shared/src/schemas/index.ts
  packages/shared/src/schemas/link-schemas.ts
  packages/worker/assets/migrations/00011-create-link-table.sql
  pnpm-lock.yaml
  src/app/(dashboard)/apps/page.tsx
  src/app/(dashboard)/components/AddLink/AddLinkButton.tsx
  src/app/(dashboard)/components/AddLink/AddLinkModal.tsx
  src/app/(dashboard)/components/AddLink/DeleteLinkModal.tsx
  src/app/(dashboard)/components/AddLink/addLink.module.css
  src/app/actions/custom-links/add-link-action.ts
  src/app/actions/custom-links/delete-link-action.ts
  src/app/actions/custom-links/edit-link-action.ts
  src/client/components/AppLogo/AppLogo.tsx
  src/client/components/LinkTile/LinkTile.tsx
  src/client/components/ui/ContextMenu/ContextMenu.tsx
  src/client/messages/en.json
  src/server/db/schema.ts
  src/server/queries/links/links.queries.ts
  src/server/services/custom-links/custom-links.service.ts
Labels: size/XL

#1207 New Crowdin updates
  src/client/messages/af-ZA.json
  src/client/messages/ar-SA.json
  src/client/messages/ca-ES.json
  src/client/messages/cs-CZ.json
  src/client/messages/da-DK.json
  src/client/messages/de-DE.json
  src/client/messages/el-GR.json
  src/client/messages/en-US.json
  src/client/messages/es-ES.json
  src/client/messages/fi-FI.json
  src/client/messages/fr-FR.json
  src/client/messages/he-IL.json
  src/client/messages/hu-HU.json
  src/client/messages/it-IT.json
  src/client/messages/ja-JP.json
  src/client/messages/ko-KR.json
  src/client/messages/nl-NL.json
  src/client/messages/no-NO.json
  src/client/messages/pl-PL.json
  src/client/messages/pt-BR.json
  src/client/messages/pt-PT.json
  src/client/messages/ro-RO.json
  src/client/messages/ru-RU.json
  src/client/messages/sr-SP.json
  src/client/messages/sv-SE.json
  src/client/messages/tr-TR.json
  src/client/messages/uk-UA.json
  src/client/messages/vi-VN.json
  src/client/messages/zh-CN.json
  src/client/messages/zh-TW.json
Labels: size/XL

#1216 chore: fix contributors badge on readme
  README.md
Labels: size/XS

#1217 Revert "chore: fix contributors badge on readme"
  README.md
Labels: size/XS

#1218 refactor(addlinkmodal): use different translation
  src/app/(dashboard)/components/AddLink/AddLinkModal.tsx
  src/client/messages/en.json
Labels: size/XS

#1223 Master
  .github/workflows/alpha-release.yml
  docker-compose.dev.yml
  docker-compose.prod.yml
  packages/shared/src/helpers/error-helpers.ts
  packages/worker/Dockerfile
  packages/worker/assets/traefik/traefik.yml
  packages/worker/src/services/repo/repo.executors.ts
  scripts/install.sh
  scripts/update-2.0.0-to-3.0.0.sh
  src/app/components/ClientProviders/SocketProvider/SocketProvider.ts
  src/lib/socket/useSocket.ts
Labels: size/L

#1227 fix(worker): permission issue in app data folder
  package.json
  packages/worker/src/services/app/app.executors.ts
Labels: size/XS

#1233 Release/3.0.2
  package.json
  packages/worker/src/lib/system/system.helpers.ts
  src/server/core/TipiConfig/TipiConfig.ts
Labels: size/XS

#1228 fix/populate-select-fields
  src/app/(dashboard)/app-store/[id]/components/InstallForm/InstallForm.tsx
Labels: bug, size/XS

#1214 New Crowdin updates
  src/client/messages/af-ZA.json
  src/client/messages/ar-SA.json
  src/client/messages/ca-ES.json
  src/client/messages/cs-CZ.json
  src/client/messages/da-DK.json
  src/client/messages/de-DE.json
  src/client/messages/el-GR.json
  src/client/messages/en-US.json
  src/client/messages/es-ES.json
  src/client/messages/fi-FI.json
  src/client/messages/fr-FR.json
  src/client/messages/he-IL.json
  src/client/messages/hu-HU.json
  src/client/messages/it-IT.json
  src/client/messages/ja-JP.json
  src/client/messages/ko-KR.json
  src/client/messages/nl-NL.json
  src/client/messages/no-NO.json
  src/client/messages/pl-PL.json
  src/client/messages/pt-BR.json
  src/client/messages/pt-PT.json
  src/client/messages/ro-RO.json
  src/client/messages/ru-RU.json
  src/client/messages/sr-SP.json
  src/client/messages/sv-SE.json
  src/client/messages/tr-TR.json
  src/client/messages/uk-UA.json
  src/client/messages/vi-VN.json
  src/client/messages/zh-CN.json
  src/client/messages/zh-TW.json
Labels: size/XL

#1252 chore: kill node cli
  package.json
  packages/cli/.env.test
  packages/cli/.eslintignore
  packages/cli/.eslintrc.js
  packages/cli/.gitignore
  packages/cli/.prettierrc.js
  packages/cli/VERSION
  packages/cli/build.js
  packages/cli/nodemon.json
  packages/cli/package.json
  packages/cli/src/executors/app/app.executors.ts
  packages/cli/src/executors/index.ts
  packages/cli/src/executors/system/system.executors.ts
  packages/cli/src/executors/system/system.helpers.ts
  packages/cli/src/index.ts
  packages/cli/src/utils/environment/environment.ts
  packages/cli/src/utils/exec-async/execAsync.tsx
  packages/cli/src/utils/logger/logger.ts
  packages/cli/src/utils/logger/terminal-spinner.ts
  packages/cli/tests/apps.factory.ts
  packages/cli/tests/mocks/fs.ts
  packages/cli/tests/vite.setup.ts
  packages/cli/tsconfig.json
  packages/cli/vitest.config.ts
  pnpm-lock.yaml
Labels: size/XXL

#1250 New Crowdin updates
  src/client/messages/zh-CN.json
Labels: size/S
