Repository runtipi/runtipi, pull requests merged in 2024-05, with the labels that each got.

#1390 chore: downgrade to pnpm v8
  pnpm-lock.yaml
Labels: size/XXL

#1389 feat: add tipi minimum version requirement when installing and updating
  docker-compose.dev.yml
  docker-compose.prod.yml
  packages/shared/src/schemas/app-schemas.ts
  packages/worker/src/services/app/app.executors.ts
  src/client/messages/en.json
  src/server/core/TipiConfig/TipiConfig.ts
  src/server/services/apps/apps.helpers.ts
  src/server/services/apps/apps.service.test.ts
  src/server/services/apps/apps.service.ts
  start.dev.sh
Labels: size/L

#1386 feat(dashboard): add warning if internal ip is public
  package.json
  pnpm-lock.yaml
  src/app/(dashboard)/components/AtRiskBanner/AtRiskBanner.tsx
  src/app/(dashboard)/layout.tsx
  src/app/components/OffCanvas/OffCanvas.tsx
  src/client/messages/en.json
  src/server/utils/network.ts
Labels: size/L

#1387 New Crowdin updates
  src/client/messages/af-ZA.json
  src/client/messages/ar-SA.json
  src/client/messages/ca-ES.json
  src/client/messages/cs-CZ.json
  src/client/messages/da-DK.json
  src/client/messages/de-DE.json
  src/client/messages/el-GR.json
  src/client/messages/en-US.json
  src/client/messages/es-ES.json
  src/client/messages/fi-FI.json
  src/client/messages/fr-FR.json
  src/client/messages/he-IL.json
  src/client/messages/hu-HU.json
  src/client/messages/it-IT.json
  src/client/messages/ja-JP.json
  src/client/messages/ko-KR.json
  src/client/messages/nl-NL.json
  src/client/messages/no-NO.json
  src/client/messages/pl-PL.json
  src/client/messages/pt-BR.json
  src/client/messages/pt-PT.json
  src/client/messages/ro-RO.json
  src/client/messages/ru-RU.json
  src/client/messages/sr-SP.json
  src/client/messages/sv-SE.json
  src/client/messages/tr-TR.json
  src/client/messages/uk-UA.json
  src/client/messages/vi-VN.json
  src/client/messages/zh-CN.json
  src/client/messages/zh-TW.json
Labels: size/XL

#1396 New Crowdin updates
  src/client/messages/af-ZA.json
  src/client/messages/ar-SA.json
  src/client/messages/ca-ES.json
  src/client/messages/cs-CZ.json
  src/client/messages/da-DK.json
  src/client/messages/de-DE.json
  src/client/messages/el-GR.json
  src/client/messages/en-US.json
  src/client/messages/es-ES.json
  src/client/messages/fi-FI.json
  src/client/messages/fr-FR.json
  src/client/messages/he-IL.json
  src/client/messages/hu-HU.json
  src/client/messages/it-IT.json
  src/client/messages/ja-JP.json
  src/client/messages/ko-KR.json
  src/client/messages/nl-NL.json
  src/client/messages/no-NO.json
  src/client/messages/pl-PL.json
  src/client/messages/pt-BR.json
  src/client/messages/pt-PT.json
  src/client/messages/ro-RO.json
  src/client/messages/ru-RU.json
  src/client/messages/sr-SP.json
  src/client/messages/sv-SE.json
  src/client/messages/tr-TR.json
  src/client/messages/uk-UA.json
  src/client/messages/vi-VN.json
  src/client/messages/zh-CN.json
  src/client/messages/zh-TW.json
Labels: size/M

#1400 New Crowdin updates
  src/client/messages/es-ES.json
  src/client/messages/fr-FR.json
Labels: size/M

#1414 feat/section-app-install-form
  src/app/(dashboard)/app-store/[id]/components/InstallForm/InstallForm.tsx
  src/client/messages/en.json
Labels: size/XS

#1426 Update regex in install script
  scripts/install.sh
Labels: size/XS

#1436 run e2e directly in github actions
  .github/workflows/e2e-local.yml
  .github/workflows/e2e.yml
  e2e/0003-apps.spec.ts
  e2e/fixtures/fixtures.ts
  e2e/helpers/constants.ts
  e2e/helpers/settings.ts
  e2e/helpers/write-remote-file.ts
  pnpm-lock.yaml
Labels: size/XL

#1437 chore: various cleanups and deprecations fixes
  .dockerignore
  .eslintrc.js
  .gitignore
  .prettierignore
  Dockerfile
  Dockerfile.dev
  jest.config.ts
  package.json
  packages/shared/package.json
  packages/worker/package.json
  pnpm-lock.yaml
  public/js/.gitkeep
  scripts/postinstall.sh
  src/app/(dashboard)/app-store/helpers/table.types.ts
  src/app/(dashboard)/components/Header/Header.tsx
  src/app/components/ClientProviders/ClientProviders.tsx
  src/app/layout.tsx
  src/lib/themes.ts
  src/server/common/fs.helpers.ts
  src/server/utils/network.ts
Labels: size/XL

#1438 Release/3.3.1
  .all-contributorsrc
  .dockerignore
  .eslintrc.js
  .github/workflows/e2e.yml
  .gitignore
  .prettierignore
  Dockerfile
  Dockerfile.dev
  README.md
  e2e/0003-apps.spec.ts
  e2e/fixtures/fixtures.ts
  e2e/helpers/constants.ts
  e2e/helpers/settings.ts
  e2e/helpers/write-remote-file.ts
  jest.config.ts
  package.json
  packages/shared/.eslintrc.js
  packages/shared/package.json
  packages/worker/.eslintrc.js
  packages/worker/package.json
  packages/worker/src/index.ts
  packages/worker/src/services/app/__tests__/app.helpers.test.ts
  packages/worker/src/services/app/app.executors.ts
  packages/worker/src/watcher/watcher.ts
  pnpm-lock.yaml
  public/js/.gitkeep
  scripts/install.sh
  scripts/postinstall.sh
  src/app/(dashboard)/app-store/[id]/components/InstallForm/InstallFormField.tsx
  src/app/(dashboard)/app-store/helpers/table.types.ts
  src/app/(dashboard)/components/Header/Header.tsx
  src/app/actions/custom-links/delete-link-action.ts
  src/app/components/ClientProviders/ClientProviders.tsx
  src/app/components/ClientProviders/ThemeProvider/ThemeProvider.tsx
  src/app/layout.tsx
  src/client/components/ui/Dialog/Dialog.tsx
  src/client/components/ui/Select/Select.tsx
  src/client/mocks/index.ts
  src/lib/themes.ts
  src/server/common/fs.helpers.ts
  src/server/core/EventDispatcher/EventDispatcher.ts
  src/server/core/TipiConfig/TipiConfig.test.ts
  src/server/services/apps/apps.helpers.test.ts
  src/server/services/apps/apps.service.ts
  src/server/tests/test-utils.ts
  src/server/utils/__tests__/encryption.test.ts
  src/server/utils/network.ts
Labels: size/XXL

#1439 Release/3.3.1
  .github/workflows/e2e.yml
  package.json
Labels: size/XS

#1440 Release/3.3.1
  .github/workflows/e2e.yml
  package.json
Labels: size/XS

#1445 feat: view app logs in dashboard
  packages/shared/src/schemas/socket-schemas.ts
  packages/worker/src/lib/docker/docker-helpers.ts
  packages/worker/src/lib/socket/SocketManager.ts
  src/app/(dashboard)/app-store/[id]/components/AppDetailsContainer/AppDetailsContainer.tsx
  src/app/(dashboard)/app-store/[id]/components/AppDetailsTabs/AppDetailsTabs.tsx
  src/app/(dashboard)/app-store/[id]/components/AppDetailsTabs/LogsTerminal.module.scss
  src/app/(dashboard)/app-store/[id]/components/AppDetailsTabs/LogsTerminal.tsx
  src/client/messages/en.json
  src/client/messages/es-ES.json
  src/lib/socket/useSocket.test.ts
  src/lib/socket/useSocket.ts
  vitest.workspace.ts
Labels: size/L

#1447 Autoforward ports in codespaces
  .devcontainer/devcontainer.json
Labels: size/S

#1448 fix: sentry config
  .dockerignore
  Dockerfile
  Dockerfile.dev
  docker-compose.dev.yml
  docker-compose.prod.yml
  next.config.mjs
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/(dashboard)/test-error/page.tsx
  src/app/api/test-error/route.ts
  src/app/global-error.jsx
  src/app/global-error.tsx
  src/instrumentation.ts
Labels: size/L

#1450 Feat/tipi logs terminal
  docker-compose.dev.yml
  docker-compose.prod.yml
  package.json
  packages/shared/src/schemas/socket-schemas.ts
  packages/worker/src/lib/docker/docker-helpers.ts
  packages/worker/src/lib/socket/SocketManager.ts
  src/app/(dashboard)/app-store/[id]/components/AppDetailsTabs/AppDetailsTabs.tsx
  src/app/(dashboard)/app-store/[id]/components/AppDetailsTabs/AppLogs.tsx
  src/app/(dashboard)/settings/components/LogsContainer/LogsContainer.tsx
  src/app/(dashboard)/settings/components/LogsContainer/index.ts
  src/app/(dashboard)/settings/components/SettingsTabTriggers/SettingsTabTriggers.tsx
  src/app/(dashboard)/settings/page.tsx
  src/app/components/LogsTerminal/LogsTerminal.module.scss
  src/app/components/LogsTerminal/LogsTerminal.tsx
  src/client/messages/en.json
  src/lib/socket/useSocket.test.ts
  src/lib/socket/useSocket.ts
Labels: size/L
