Repository runtipi/runtipi, pull requests merged in 2025-05, with the labels that each got.

#2133 feat(guest-dashboard): download certificate button
  .gitignore
  packages/backend/src/modules/i18n/translations/en-US.json
  packages/backend/src/modules/i18n/translations/en.json
  packages/backend/src/modules/system/system.controller.ts
  packages/frontend/src/components/header/guest-header.tsx
Labels: size/S

#2140 refactor(subnet-manager): list used networks from docker instead of db
  packages/backend/build.mjs
  packages/backend/package.json
  packages/backend/src/core/database/drizzle/0021_mighty_molecule_man.sql
  packages/backend/src/core/database/drizzle/meta/0021_snapshot.json
  packages/backend/src/core/database/drizzle/meta/_journal.json
  packages/backend/src/core/database/drizzle/schema.ts
  packages/backend/src/modules/app-lifecycle/app-lifecycle-command.factory.ts
  packages/backend/src/modules/app-lifecycle/commands/command.ts
  packages/backend/src/modules/app-lifecycle/commands/restore-app-command.ts
  packages/backend/src/modules/app-lifecycle/commands/update-app-command.ts
  packages/backend/src/modules/docker/builders/__tests__/__snapshots__/compose.builder.test.ts.snap
  packages/backend/src/modules/docker/builders/__tests__/compose.builder.test.ts
  packages/backend/src/modules/docker/builders/compose.builder.ts
  packages/backend/src/modules/docker/docker.module.ts
  packages/backend/src/modules/network/__tests__/subnet-manager.service.test.ts
  packages/backend/src/modules/network/network.module.ts
  packages/backend/src/modules/network/subnet-manager.service.ts
  packages/backend/src/tests/integration/__snapshots__/app-lifecycle.test.ts.snap
  packages/backend/src/tests/integration/app-lifecycle.test.ts
  packages/backend/vitest.config.mts
  pnpm-lock.yaml
Labels: size/XL

#2110 refactor: move internal local folders to .internal
  .gitignore
  .internal/cache/.gitkeep
  Dockerfile
  Dockerfile.dev
  biome.json
  docker-compose.dev.yml
  docker-compose.prod.yml
  package.json
  packages/common/package.json
  turbo.json
Labels: size/M

#2151 feat(links): visible on guest dashboard
  .gitignore
  docs/external-links.md
  docs/guest-dashboard.md
  packages/backend/src/core/database/drizzle/0023_petite_marauders.sql
  packages/backend/src/core/database/drizzle/meta/0023_snapshot.json
  packages/backend/src/core/database/drizzle/meta/_journal.json
  packages/backend/src/core/database/drizzle/schema.ts
  packages/backend/src/metadata.ts
  packages/backend/src/modules/links/dto/links.dto.ts
  packages/backend/src/modules/links/links.controller.ts
  packages/backend/src/modules/links/links.repository.ts
  packages/backend/src/modules/links/links.service.ts
  packages/backend/src/swagger.json
  packages/frontend/src/api-client/@tanstack/react-query.gen.ts
  packages/frontend/src/api-client/sdk.gen.ts
  packages/frontend/src/api-client/types.gen.ts
  packages/frontend/src/modules/app/components/dialogs/add-link/add-link-dialog.tsx
  packages/frontend/src/modules/dashboard/components/guest-link-tile.tsx
  packages/frontend/src/modules/dashboard/pages/guest-dashboard.tsx
Labels: size/XXL

#2152 fix(guest-dashboard): open custom local subdomain
  packages/backend/src/app.controller.ts
  packages/backend/src/app.dto.ts
  packages/backend/src/modules/apps/apps.controller.ts
  packages/backend/src/modules/apps/apps.service.ts
  packages/backend/src/modules/apps/dto/app.dto.ts
  packages/backend/src/modules/docker/builders/compose.builder.ts
  packages/backend/src/modules/docker/builders/traefik-labels.builder.ts
  packages/backend/src/modules/marketplace/dto/marketplace.dto.ts
  packages/backend/src/swagger.json
  packages/frontend/src/api-client/types.gen.ts
  packages/frontend/src/modules/app/containers/app-actions/app-actions.tsx
  packages/frontend/src/modules/dashboard/pages/guest-dashboard.tsx
Labels: size/L

#2154 fix(install.sh): update RPM-based package manager commands
  scripts/install.sh
Labels: size/S

#2132 New Crowdin updates
  packages/backend/src/modules/i18n/translations/af-ZA.json
  packages/backend/src/modules/i18n/translations/ar-SA.json
  packages/backend/src/modules/i18n/translations/ca-ES.json
  packages/backend/src/modules/i18n/translations/cs-CZ.json
  packages/backend/src/modules/i18n/translations/da-DK.json
  packages/backend/src/modules/i18n/translations/de-DE.json
  packages/backend/src/modules/i18n/translations/el-GR.json
  packages/backend/src/modules/i18n/translations/en-US.json
  packages/backend/src/modules/i18n/translations/es-ES.json
  packages/backend/src/modules/i18n/translations/fi-FI.json
  packages/backend/src/modules/i18n/translations/fr-FR.json
  packages/backend/src/modules/i18n/translations/he-IL.json
  packages/backend/src/modules/i18n/translations/hu-HU.json
  packages/backend/src/modules/i18n/translations/it-IT.json
  packages/backend/src/modules/i18n/translations/ja-JP.json
  packages/backend/src/modules/i18n/translations/ko-KR.json
  packages/backend/src/modules/i18n/translations/nl-NL.json
  packages/backend/src/modules/i18n/translations/no-NO.json
  packages/backend/src/modules/i18n/translations/pl-PL.json
  packages/backend/src/modules/i18n/translations/pt-BR.json
  packages/backend/src/modules/i18n/translations/pt-PT.json
  packages/backend/src/modules/i18n/translations/ro-RO.json
  packages/backend/src/modules/i18n/translations/ru-RU.json
  packages/backend/src/modules/i18n/translations/sr-SP.json
  packages/backend/src/modules/i18n/translations/sv-SE.json
  packages/backend/src/modules/i18n/translations/tr-TR.json
  packages/backend/src/modules/i18n/translations/uk-UA.json
  packages/backend/src/modules/i18n/translations/vi-VN.json
  packages/backend/src/modules/i18n/translations/zh-CN.json
  packages/backend/src/modules/i18n/translations/zh-TW.json
Labels: size/XL

#2181 fix: use correct port in guest dashboard
  packages/frontend/src/modules/dashboard/pages/guest-dashboard.tsx
Labels: size/S

#2165 refactor: improve icons
  packages/frontend/index.html
  packages/frontend/public/icons/android-chrome-192x192.png
  packages/frontend/public/icons/android-chrome-512x512.png
  packages/frontend/public/icons/apple-touch-icon.png
  packages/frontend/public/icons/favicon-16x16.png
  packages/frontend/public/icons/favicon-32x32.png
  packages/frontend/public/icons/favicon-96x96.png
  packages/frontend/public/icons/favicon.ico
  packages/frontend/public/icons/favicon.svg
  packages/frontend/public/icons/site.webmanifest
  packages/frontend/public/icons/web-app-manifest-192x192.png
  packages/frontend/public/icons/web-app-manifest-512x512.png
Labels: size/M

#2192 fix: ignore current app in port check
  packages/backend/src/modules/app-lifecycle/app-lifecycle.service.ts
Labels: size/XS

#2191 fix: fix theme toggle in guest dashboard
  packages/frontend/src/components/header/guest-header.tsx
Labels: size/S

#2189 feat: use configured domain as a placeholder in expose
  packages/frontend/src/modules/app/components/install-form/install-form.tsx
Labels: size/XS
