Repository runtipi/runtipi, pull requests merged in 2025-03, with the labels that each got.

#2001 chore: update sentry dependencies
  packages/backend/package.json
  packages/frontend/package.json
  pnpm-lock.yaml
Labels: size/S

#2036 fix: use app urn in local domain
  packages/frontend/src/modules/app/containers/app-actions/app-actions.tsx
Labels: size/XS

#2002 New Crowdin updates
  packages/backend/src/modules/i18n/translations/af-ZA.json
  packages/backend/src/modules/i18n/translations/ar-SA.json
  packages/backend/src/modules/i18n/translations/ca-ES.json
  packages/backend/src/modules/i18n/translations/cs-CZ.json
  packages/backend/src/modules/i18n/translations/da-DK.json
  packages/backend/src/modules/i18n/translations/de-DE.json
  packages/backend/src/modules/i18n/translations/el-GR.json
  packages/backend/src/modules/i18n/translations/en-US.json
  packages/backend/src/modules/i18n/translations/es-ES.json
  packages/backend/src/modules/i18n/translations/fi-FI.json
  packages/backend/src/modules/i18n/translations/fr-FR.json
  packages/backend/src/modules/i18n/translations/he-IL.json
  packages/backend/src/modules/i18n/translations/hu-HU.json
  packages/backend/src/modules/i18n/translations/it-IT.json
  packages/backend/src/modules/i18n/translations/ja-JP.json
  packages/backend/src/modules/i18n/translations/ko-KR.json
  packages/backend/src/modules/i18n/translations/nl-NL.json
  packages/backend/src/modules/i18n/translations/no-NO.json
  packages/backend/src/modules/i18n/translations/pl-PL.json
  packages/backend/src/modules/i18n/translations/pt-BR.json
  packages/backend/src/modules/i18n/translations/pt-PT.json
  packages/backend/src/modules/i18n/translations/ro-RO.json
  packages/backend/src/modules/i18n/translations/ru-RU.json
  packages/backend/src/modules/i18n/translations/sr-SP.json
  packages/backend/src/modules/i18n/translations/sv-SE.json
  packages/backend/src/modules/i18n/translations/tr-TR.json
  packages/backend/src/modules/i18n/translations/uk-UA.json
  packages/backend/src/modules/i18n/translations/vi-VN.json
  packages/backend/src/modules/i18n/translations/zh-CN.json
  packages/backend/src/modules/i18n/translations/zh-TW.json
Labels: size/XXL

#2047 feat: qol updates
  packages/backend/src/modules/i18n/translations/en-US.json
  packages/backend/src/modules/i18n/translations/en.json
  packages/frontend/src/components/layouts/dashboard/layout.tsx
  packages/frontend/src/components/timezone-selector/timezone-selector.css
  packages/frontend/src/components/ui/Select/Select.tsx
  packages/frontend/src/modules/settings/components/add-app-store-dialog/add-app-store-dialog.tsx
  packages/frontend/src/modules/settings/components/app-stores-table/app-stores-table.tsx
  packages/frontend/src/modules/settings/components/delete-app-store-dialog/delete-app-store-dialog.tsx
  packages/frontend/src/modules/settings/components/edit-app-store-dialog/edit-app-store-dialog.tsx
  packages/frontend/src/modules/settings/containers/app-stores-container.tsx
Labels: size/M

#2037 feat: add dropdown to tabs when screen size is too small
  packages/backend/src/modules/i18n/translations/en-US.json
  packages/backend/src/modules/i18n/translations/en.json
  packages/frontend/src/modules/app/containers/app-details-tabs/app-details-tabs.tsx
  packages/frontend/src/modules/settings/pages/settings-page.tsx
Labels: size/M

#2048 Feat/qol updates
  packages/backend/src/app.service.ts
  packages/backend/src/modules/app-stores/repos.helpers.ts
Labels: size/XS

#2044 New Crowdin updates
  packages/backend/src/modules/i18n/translations/uk-UA.json
Labels: size/XS

#2042 feat: add container name to dynamic compose
  packages/backend/src/modules/docker/builders/__tests__/__snapshots__/compose.builder.test.ts.snap
  packages/backend/src/modules/docker/builders/compose.builder.ts
  packages/backend/src/modules/docker/builders/service.builder.ts
  packages/backend/src/tests/integration/__snapshots__/app-lifecycle.test.ts.snap
Labels: size/M

#2054 fix: dynamic import error
  packages/frontend/src/main.tsx
Labels: size/XS

#2057 fix: use correct local domain in guest dash
  packages/frontend/src/modules/dashboard/pages/guest-dashboard.tsx
  packages/frontend/src/types/app.types.ts
  packages/frontend/src/utils/app-helpers.ts
Labels: size/S

#2058 fix(docker.service): remove usage of docker-compose.common.yml
  packages/backend/src/modules/docker/docker.service.ts
Labels: size/XS
