Repository runtipi/runtipi, pull requests merged in 2025-02, with the labels that each got.

#1955 Changed language selection cookie to expire from session to 365 days
  packages/frontend/src/components/language-selector/language-selector.tsx
Labels: size/XS

#1971 feat(app-lifecycle): start all running apps on start
  packages/backend/src/app.service.ts
  packages/backend/src/modules/app-lifecycle/app-lifecycle.service.ts
Labels: size/S

#1976 feat: add local domain to guest dashboard
  packages/backend/src/metadata.ts
  packages/backend/src/modules/apps/apps.controller.ts
  packages/backend/src/modules/apps/apps.module.ts
  packages/backend/src/modules/apps/dto/app.dto.ts
  packages/backend/src/swagger.json
  packages/frontend/src/api-client/@tanstack/react-query.gen.ts
  packages/frontend/src/api-client/sdk.gen.ts
  packages/frontend/src/api-client/types.gen.ts
  packages/frontend/src/modules/dashboard/pages/guest-dashboard.tsx
  scripts/nuke.sh
Labels: size/L

#1981 fix: enable scrolling on guest dashboard
  packages/frontend/src/modules/dashboard/pages/guest-dashboard.tsx
Labels: size/M

#1985 fix: fix scrolling on guest dashboard
  packages/frontend/src/modules/dashboard/pages/guest-dashboard.tsx
Labels: size/S

#1986 Release: 3.9.2
  e2e/0005-guest-dashboard.spec.ts
  package.json
  packages/backend/src/common/constants.ts
  packages/backend/src/common/helpers/env-helpers.ts
  packages/backend/src/modules/auth/auth.controller.ts
  packages/backend/src/modules/auth/auth.middleware.ts
  packages/backend/src/modules/i18n/translations/af-ZA.json
  packages/backend/src/modules/i18n/translations/ar-SA.json
  packages/backend/src/modules/i18n/translations/ca-ES.json
  packages/backend/src/modules/i18n/translations/cs-CZ.json
  packages/backend/src/modules/i18n/translations/da-DK.json
  packages/backend/src/modules/i18n/translations/de-DE.json
  packages/backend/src/modules/i18n/translations/el-GR.json
  packages/backend/src/modules/i18n/translations/es-ES.json
  packages/backend/src/modules/i18n/translations/fi-FI.json
  packages/backend/src/modules/i18n/translations/fr-FR.json
  packages/backend/src/modules/i18n/translations/he-IL.json
  packages/backend/src/modules/i18n/translations/hu-HU.json
  packages/backend/src/modules/i18n/translations/it-IT.json
  packages/backend/src/modules/i18n/translations/ja-JP.json
  packages/backend/src/modules/i18n/translations/ko-KR.json
  packages/backend/src/modules/i18n/translations/nl-NL.json
  packages/backend/src/modules/i18n/translations/no-NO.json
  packages/backend/src/modules/i18n/translations/pl-PL.json
  packages/backend/src/modules/i18n/translations/pt-BR.json
  packages/backend/src/modules/i18n/translations/pt-PT.json
  packages/backend/src/modules/i18n/translations/ro-RO.json
  packages/backend/src/modules/i18n/translations/ru-RU.json
  packages/backend/src/modules/i18n/translations/sr-SP.json
  packages/backend/src/modules/i18n/translations/sv-SE.json
  packages/backend/src/modules/i18n/translations/tr-TR.json
  packages/backend/src/modules/i18n/translations/uk-UA.json
  packages/backend/src/modules/i18n/translations/vi-VN.json
  packages/backend/src/modules/i18n/translations/zh-CN.json
  packages/backend/src/modules/i18n/translations/zh-TW.json
  packages/frontend/src/modules/dashboard/pages/guest-dashboard.tsx
  packages/frontend/src/modules/settings/components/user-settings-form/user-settings-form.tsx
  playwright.config.ts
Labels: size/L

#1988 Release 3.9.3
  .github/workflows/beta-release.yml
  .github/workflows/release.yml
  package.json
  packages/backend/package.json
  packages/backend/src/core/cache/cache.service.ts
  packages/backend/src/core/config/configuration.service.ts
  packages/backend/src/modules/auth/auth.controller.ts
  packages/backend/src/modules/auth/auth.service.ts
  playwright.config.ts
  pnpm-lock.yaml
Labels: size/L

#1994 Release/3.9.4
  .github/actions/install-dependencies/action.yml
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
  Dockerfile
  Dockerfile.dev
  package.json
  packages/backend/build.mjs
  packages/backend/package.json
  packages/backend/src/__tests__/app.service.test.ts
  packages/backend/src/app.service.ts
  packages/backend/src/core/cache/cache.service.ts
  packages/backend/src/modules/auth/__tests__/auth.service.test.ts
  packages/backend/src/modules/auth/auth.controller.ts
  packages/backend/src/modules/auth/auth.middleware.ts
  packages/backend/src/modules/auth/auth.service.ts
  packages/backend/src/modules/auth/session.manager.ts
  packages/backend/vitest.config.mts
  pnpm-lock.yaml
Labels: size/L
