Repository runtipi/runtipi, pull requests merged in 2025-04, with the labels that each got.

#2061 chore: debug
  .github/workflows/translations.yml
Labels: size/S

#2065 refactor: throw error when compose.json fails to generate
  packages/backend/src/modules/app-lifecycle/commands/command.ts
Labels: size/S

#2050 New Crowdin updates
  packages/backend/src/modules/i18n/translations/af-ZA.json
  packages/backend/src/modules/i18n/translations/ar-SA.json
  packages/backend/src/modules/i18n/translations/ca-ES.json
  packages/backend/src/modules/i18n/translations/cs-CZ.json
  packages/backend/src/modules/i18n/translations/da-DK.json
  packages/backend/src/modules/i18n/translations/de-DE.json
  packages/backend/src/modules/i18n/translations/el-GR.json
  packages/backend/src/modules/i18n/translations/es-ES.json
  packages/backend/src/modules/i18n/translations/fi-FI.json
  packages/backend/src/modules/i18n/translations/fr-FR.json
  packages/backend/src/modules/i18n/translations/he-IL.json
  packages/backend/src/modules/i18n/translations/hu-HU.json
  packages/backend/src/modules/i18n/translations/it-IT.json
  packages/backend/src/modules/i18n/translations/ja-JP.json
  packages/backend/src/modules/i18n/translations/ko-KR.json
  packages/backend/src/modules/i18n/translations/nl-NL.json
  packages/backend/src/modules/i18n/translations/no-NO.json
  packages/backend/src/modules/i18n/translations/pl-PL.json
  packages/backend/src/modules/i18n/translations/pt-BR.json
  packages/backend/src/modules/i18n/translations/pt-PT.json
  packages/backend/src/modules/i18n/translations/ro-RO.json
  packages/backend/src/modules/i18n/translations/ru-RU.json
  packages/backend/src/modules/i18n/translations/sr-SP.json
  packages/backend/src/modules/i18n/translations/sv-SE.json
  packages/backend/src/modules/i18n/translations/tr-TR.json
  packages/backend/src/modules/i18n/translations/uk-UA.json
  packages/backend/src/modules/i18n/translations/vi-VN.json
  packages/backend/src/modules/i18n/translations/zh-CN.json
  packages/backend/src/modules/i18n/translations/zh-TW.json
Labels: size/XXL

#2078 chore: restore .env.example
  .env.example
Labels: size/M

#2080 Improve version upgrade script
  scripts/update-3.0.0-to-4.0.0.sh
Labels: size/M

#2083 refactor: improve pwa ux
  packages/frontend/index.html
  packages/frontend/public/icons/android-chrome-192x192.png
  packages/frontend/public/icons/android-chrome-512x512.png
  packages/frontend/public/icons/apple-touch-icon.png
  packages/frontend/public/icons/favicon-16x16.png
  packages/frontend/public/icons/favicon-32x32.png
  packages/frontend/public/icons/favicon-96x96.png
  packages/frontend/public/icons/favicon.ico
  packages/frontend/public/icons/favicon.svg
  packages/frontend/public/icons/site.webmanifest
  packages/frontend/public/icons/web-app-manifest-192x192.png
  packages/frontend/public/icons/web-app-manifest-512x512.png
Labels: size/M

#2095 fix: use tabler's new styles for alerts
  packages/frontend/src/components/ui/Alert/Alert.tsx
  packages/frontend/src/modules/app/components/dialogs/install-dialog/install-dialog.tsx
  packages/frontend/src/modules/app/containers/app-details-tabs/app-details-tabs.tsx
  packages/frontend/src/modules/settings/components/user-settings-form/user-settings-form.tsx
  packages/frontend/src/modules/settings/containers/app-stores-container.tsx
Labels: size/M

#2093 fix: downgrade swc cli
  packages/backend/package.json
  pnpm-lock.yaml
Labels: size/XS

#2102 refactor: reset proxy settings if app is not exposable
  packages/backend/src/modules/app-lifecycle/app-lifecycle.service.ts
Labels: size/S

#2099 feat: add app id and app store id env variables
  packages/backend/src/modules/apps/app.helpers.ts
Labels: size/XS

#2112 Fix/store-selector
  packages/frontend/src/components/store-selector/store-selector.tsx
Labels: size/S
